### ISSUE TITLE
remove_local_imports not defined error

### ISSUE THREAD

**Issue by avinashkarhana** [Nicolas-Reyland/findpydeps#1]
When trying `findpydeps -i . ` throws remove_local_imports not defined error

**Comment by Nicolas-Reyland** [comment]
Hi, I am re-doing great parts of the project right now. Once I'm finished (and I"ll tell you), I'll test the tool thoroughly !
I hope this error will have been removed. Thank you for telling me tho !

**Comment by Nicolas-Reyland** [comment]
Hi, normally if you run `pip install --upgrade findpydeps` you should not get this error again. I tested it on my setup and the command `findpydeps -i .` worked. I'm closing this issue, but feel free to open a new one if another (or the same??) error comes up !
Have a nice day

**Comment by Nicolas-Reyland** [comment]
> When trying `findpydeps -i . ` throws remove_local_imports not defined error

Hi, normally if you run pip install --upgrade findpydeps you should not get this error again. I tested it on my setup and the command findpydeps -i . worked. I'm closing this issue, but feel free to open a new one if another (or the same??) error comes up !
Have a nice day
