### ISSUE TITLE
Dependency tree

### ISSUE THREAD

**Issue by buhtz** [Nicolas-Reyland/findpydeps#2]
Hi,

this is a great package you have here. I assume my wish isn't easy.

It would help a lot of I could see a dependency graph. I would like to know on what my dependencies are depending on and so on.

Use-case: One of my dependencies seems to import pandas or numpy. But I don't know which one.

**Comment by Nicolas-Reyland** [comment]
Would be absolutely possible. If I have some time to spare this weekend, I'll try to look into it. Maybe you can try to make a PR for it ?
